### ISSUE TITLE
Can find a way to share the validation logic with .NET backend?

### ISSUE THREAD

**Issue by janvanderhaegen** [janvanderhaegen/aurelia-validation#32]
Would make it easy to reuse validation server-side for asp.net apps.

**Comment by ShaneCourtrille** [comment]
Just as a point of fact ASP.Net MVC/Web API which is what you would use with Aurelia already has built in validation which integrates very well into the MS experience so I'm not sure this has a huge value?

**Comment by janvanderhaegen** [comment]
Hey @ShaneCourtrille , that's a really good point...
Instead of a direct port, I really meant (and changed the title accordingly) to open the discussion and poll for ideas on how we can share the validation logic client/server side. For example, based on the MVC/Web API validation (EF?), can we generate all or part of the logic so that developers would not have to "duplicate" themselves?
If so, what would be acceptable/doable/smartest?
A code-generating build-task?  On demand scaffolding? A controller that returns the logic (JSON form), which we then feed into the Validation plugin?
