### ISSUE TITLE
validationProperty.js has incorrect filename capitalisation

### ISSUE THREAD

**Issue by RichardMullins** [janvanderhaegen/aurelia-validation#34]
The ValidationProperty.js  in /src/validation/ file has a capital V

but in /src/validation/validationGroupBuilder.js on line 3 you have

```import {ValidationProperty} from '../validation/validationProperty';```

validationProperty with a lowercase v.

changing the filename fixed the problem for me.

**Comment by janvanderhaegen** [comment]
pushed&commit the modified capitalization on the filename. Stupid IDE didn't pick that up :( Thanks for the heads up!
