### ISSUE TITLE
AJAX validation support

### ISSUE THREAD

**Issue by devmondo** [janvanderhaegen/aurelia-validation#35]
i dont know if i missed it or it is not there yet, but AJAX validation is really needed, specially for cases where you want to check duplicate username on server in create account scenarios 

thanks in advanced.

**Comment by janvanderhaegen** [comment]
Absolutely amazing idea.
I'm thinking about the best way to implement this async story (do we consider this property invalid until the promise has executed?), but defo love to see this happening!

**Comment by janvanderhaegen** [comment]
Closed after moving repository to the official aurelia one: https://github.com/aurelia/validation/issues/3
